export enum ProductCategoryEnum {
  GAMES = 'Gaming',
  SMARTPHONES = 'Smartphones',
  IPHONE = 'Iphone',
  INFORMATICA = 'Informática',
  ELECTRODOMESTICS = 'Electrodomésticos',
  ELECTRONICS = 'Electrónicos',
  APPLIENCES = 'Accesorios',
  BEAUTY = 'Perfumeria & Cosmeticos',
  BEBIDAS = 'Bebidas & Cigarros',
  SPORTS = 'Deportes & Fitness',
  FASHION = 'Ropas & Calzados',
  HOME = 'Hogar & Jardin',
  CAMPING = 'Pesaca y Camping',
  TOYS = 'Juguetes & Coleccionables',
  HEALTH = 'Salud & Bienestar',
  AUTOMOTIVE = 'Automotor',
  OTHER = 'Otros',
}