### Crear preferencia de pago en Mercado Pago
POST http://localhost:3000/api/v1/payments/mercadopago/preference
Content-Type: application/json

{
  "products": [
    {
      "id": "001",
      "title": "Camiseta ChillHop",
      "quantity": 1,
      "price": 299,
      "discount": 10,
      "description": "Camiseta edición limitada",
      "category": "Ropa",
      "coupon": 0
    }
  ],
  "tenancy": {
    "api_key": "APP_USR-8274839262963894-032900-6f9d88f73d5ae9e61f886f8ea5b250e3-2517431499",
    "domain": "https://tu-dominio.com",
    "company": "ChillHop Studio"
  }
}

### Consultar una preferecia creada en Mercado Pago
GET https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=280626182-bbf2bf35-7ec4-4cee-b57e-56228269f53e


### Consultar un pago creado en Mercado Pago (HTTP request con Bearer)
GET https://api.mercadopago.com/v1/payments/152598828503
Authorization: Bearer APP_USR-8274839262963894-032900-6f9d88f73d5ae9e61f886f8ea5b250e3-2517431499